Repository kookmin-sw/2019-cap1-2019_5, pull requests merged in 2019-04, with the labels that each got.

#24 Issue#20 make rspone json format
  backend/app.js
  backend/router/v1/findRoute.js
Labels: enhancement

#28 Issue#18-relocate-files-and-refactoring
  package-lock.json
  src/backend/.gitignore
  src/backend/app.js
  src/backend/config/API_KEY_template.json
  src/backend/config/server_config_template.json
  src/backend/db.js
  src/backend/exam.json
  src/backend/lib/findRoute/byDriving.js
  src/backend/lib/findRoute/bySubway.js
  src/backend/lib/makeResult/makeResult.js
  src/backend/package-lock.json
  src/backend/package.json
  src/backend/router/index.js
  src/backend/router/v1/findRoute.js
  src/frontend/geocoding.js
  src/frontend/main.css
  src/frontend/main.html
Labels: refactoring

#30 Issue#27-bug-fix-on-main-webpage-about-API
  src/frontend/config/Api.js
  src/frontend/config/Api_template.js
Labels: bug

#32 Issue#31-add-location-candidates-file
  src/backend/.gitignore
  src/backend/location_candidates_template.json
Labels: Priority-Medium, enhancement

#35 Issue#34: response access control in index.js
  src/backend/router/index.js
  src/backend/router/v1/findRoute.js
Labels: bug

#39 Issue#36#37#38 Install react and network with server
  src/frontend/.gitignore
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/favicon.ico
  src/frontend/public/index.html
  src/frontend/public/manifest.json
  src/frontend/src/App.css
  src/frontend/src/App.js
  src/frontend/src/App.test.js
  src/frontend/src/index.css
  src/frontend/src/index.js
  src/frontend/src/serviceWorker.js
Labels: enhancement

#40 Issue#33-make-location-candidate-finder
  src/backend/lib/findRoute/find_loc_candidates.js
Labels: P0, enhancement

#42 Issue#41-send-coordinates-and-get-candidates
  src/backend/app.js
  src/backend/config/server_config_template.json
  src/backend/lib/findRoute/bySubway.js
  src/backend/lib/findRoute/find_loc_candidates.js
  src/backend/router/index.js
  src/backend/router/v1/findRoute.js
Labels: P0, enhancement, refactoring

#43 Issue#26-change-googlemap-api-to-navermap-api
  src/backend/app.js
  src/backend/package-lock.json
  src/backend/package.json
  src/frontend/geocoding.js
  src/frontend/main.css
  src/frontend/main.html
  src/frontend/package-lock.json
Labels: P0, enhancement

#46 Issue#44 sort candidate results
  src/backend/db.js
  src/backend/lib/findRoute/bySubway.js
  src/backend/router/v1/findRoute.js
Labels: P0, enhancement

#48 Issue#47-Apply-material-ui
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/index.html
  src/frontend/src/App.js
Labels: enhancement

#58 Issue#57 Fix request data type
  src/backend/router/v1/findRoute.js
  src/frontend/package-lock.json
  src/frontend/src/App.js
Labels: P0, bug

#59 Issue#56-Improve-UI-for-input-and-result-box
  src/frontend/src/App.js
Labels: P0, enhancement

#60 Issue#49 Improve result sorting algorithm
  src/backend/router/v1/findRoute.js
Labels: P0, enhancement

#63 Issue#61 Change result sorting criterion
  src/backend/router/v1/findRoute.js
Labels: P0

#64 Issue#62 revise db code for database setting
  src/backend/db.js
  src/backend/exam.json
  src/backend/lib/findRoute/find_loc_candidates.js
Labels: P1, setting

#65 Issue#62 minor refactoring
  src/backend/lib/findRoute/bySubway.js
  src/backend/router/v1/findRoute.js
Labels: P2

#66 Issue#53 show markers locations and results
  src/frontend/package-lock.json
  src/frontend/src/App.js
  src/frontend/src/FindBox.js
  src/frontend/src/Map.js
Labels: enhancement

#69 Issue#68 Add pedestrian route in public transportation
  src/backend/app.js
  src/backend/lib/findRoute/byPublic.js
  src/backend/package-lock.json
  src/backend/package.json
  src/backend/router/v1/findRoute.js
Labels: P0

#71 Issue#67 show result markers on map
  src/frontend/src/App.js
  src/frontend/src/FindBox.js
  src/frontend/src/Map.js
Labels: enhancement

#74 Issue#73-Delete unused files
  src/frontend/config/Api.js
  src/frontend/config/Api_template.js
  src/frontend/geocoding.js
  src/frontend/main.css
  src/frontend/main.html
Labels: bug

#75 Issue#72 make marker window
  src/frontend/src/Map.js
  src/frontend/src/images/location.png
  src/frontend/src/images/marker.png
  src/frontend/src/images/result-marker.png
Labels: enhancement

#77 Issue#70-Improve-result-box-ui-and-remove-button
  src/frontend/src/App.js
  src/frontend/src/FindBox.js
Labels: bug, enhancement

#78 Issue#76 make delete user function
  src/frontend/src/App.js
  src/frontend/src/FindBox.js
Labels: enhancement

#81 Issue#80-Make scroll bar in find box and Add icon for select location
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/FindBox.js
Labels: enhancement

#82 Issue#45 Improve candidate search algorithm
  src/backend/lib/findRoute/find_loc_candidates.js
Labels: P1, enhancement

#84 Issue#83 add walk as a way in travel info
  src/backend/lib/findRoute/byPublic.js
Labels: P0

#86 Issue#85 add transportation icon and place on top the button
  src/frontend/src/FindBox.js
Labels: enhancement

#88 Issue#87 marker drag and marker rank
  src/frontend/package-lock.json
  src/frontend/src/App.js
  src/frontend/src/FindBox.js
  src/frontend/src/Map.js
Labels: enhancement

#90 Issue#89 make search box
  src/backend/router/v1/findRoute.js
  src/frontend/src/Map.js
Labels: enhancement

#92 Issue#91-scrollbar-bug-fix
  src/frontend/src/FindBox.js
Labels: bug
