Repository kookmin-sw/2019-cap1-2019_5, pull requests merged in 2019-03, with the labels that each got.

#8 Issue#7 put_exam_data_in_database
  backend/db.js
  backend/package-lock.json
Labels: enhancement

#11 Issue#10 set up main web page URL
  backend/app.js
Labels: Priority-High, enhancement

#9 Issue#6 Connect server with client And Make map feature
  frontend/geocoding.js
  frontend/main.css
  frontend/main.html
Labels: enhancement

#13 Issue#5 connect driving api with server
  backend/app.js
  backend/config/API_KEY_template.json
  backend/exam.json
  backend/lib/findRoot/byCar.js
  backend/lib/findRoute/byDriving.js
  backend/lib/findRoute/bySubway.js
  backend/package-lock.json
  backend/package.json
  backend/router/index.js
  backend/router/v1/findRoute.js
  package-lock.json
Labels: Priority-High, enhancement, refactoring

#21 Issue#17 Improve driving function output
  backend/lib/findRoute/byDriving.js
Labels: Priority-High, enhancement

#23 Issue#22 hot fix in driving route finding function
  backend/lib/findRoute/byDriving.js
  backend/router/v1/findRoute.js
Labels: Priority-High, bug
