Repository kookmin-sw/2019-cap1-2019_5, pull requests merged in 2019-05, with the labels that each got.

#98 Issue#97 Transtorm to responsive web
  src/frontend/src/App.js
  src/frontend/src/FindBox.js
  src/frontend/src/Map.js
  src/frontend/src/images/logo.png
  src/frontend/src/index.js
  src/frontend/src/rwd.css
Labels: setting

#99 Issue#96 get place information
  src/backend/.gitignore
  src/backend/database/README.md
  src/backend/database/place_crawler.py
  src/backend/database/requirements.txt
  src/backend/router/v2/findRoute.js
Labels: P0, enhancement

#102 Issue#100 change responsive breakpoints and share button
  src/frontend/src/App.js
  src/frontend/src/rwd.css
Labels: setting

#106 Issue#105 add caption crawling
  src/backend/database/README.md
  src/backend/database/place_crawler.py
  src/backend/database/requirements.txt
Labels: enhancement

#113 Issue#110 make resultDB and function
  src/backend/lib/findRoute/candidatesWithUserData.js
  src/backend/lib/meeting/makeMeeting.js
  src/backend/models/Meeting.js
  src/backend/models/Result.js
  src/backend/models/index.js
  src/backend/router/v2/findRoute.js
Labels: enhancement

#104 Issue#103-Add loading logo
  src/frontend/package-lock.json
  src/frontend/src/App.js
  src/frontend/src/LoadingWindow.js
  src/frontend/src/images/logo.png
  src/frontend/src/rwd.css
Labels: enhancement

#115 Issue#114 Fix the scroll bar and make GPS icon in SearchBox
  src/frontend/src/FindBox.js
  src/frontend/src/Map.js
  src/frontend/src/rwd.css
Labels: bug

#117 Issue#116-Change-crawling-sequence
  src/backend/database/place_crawler.py
Labels: enhancement

#121 Issue#118 Final change of responsive breakpoints
  src/frontend/src/rwd.css
Labels: setting

#122 Issue#119-Add MakeRoom and PrivateRoom
  src/frontend/src/MakeRoom.css
  src/frontend/src/MakeRoom.js
  src/frontend/src/PrivateRoom.css
  src/frontend/src/PrivateRoom.js
Labels: enhancement

#124 Issue#123 make frontend version2
  src/frontend/src/index.js
  src/frontend/src/v1/App.css
  src/frontend/src/v1/App.js
  src/frontend/src/v1/App.test.js
  src/frontend/src/v1/FindBox.js
  src/frontend/src/v1/LoadingWindow.js
  src/frontend/src/v1/MakeRoom.css
  src/frontend/src/v1/MakeRoom.js
  src/frontend/src/v1/Map.js
  src/frontend/src/v1/PrivateRoom.css
  src/frontend/src/v1/PrivateRoom.js
  src/frontend/src/v1/rwd.css
  src/frontend/src/v2/App.css
  src/frontend/src/v2/App.js
  src/frontend/src/v2/App.test.js
  src/frontend/src/v2/FindBox.js
  src/frontend/src/v2/LoadingWindow.js
  src/frontend/src/v2/MakeRoom.css
  src/frontend/src/v2/MakeRoom.js
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/rwd.css
Labels: enhancement

#129 Issue#125 make frontend router
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/index.js
  src/frontend/src/v2/App.js
  src/frontend/src/v2/MakeRoom.js
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
Labels: enhancement

#131 Issue#126 enhance fetching sequence
  src/backend/.gitignore
  src/backend/database/README.md
  src/backend/database/place_crawler.py
Labels: P1

#127 add voting function using meeting name
  src/backend/db.js
  src/backend/models/CandidateLocs.js
  src/backend/models/CandidateVoting.js
  src/backend/models/index.js
  src/backend/router/index.js
  src/backend/router/v2/voting.js
Labels: enhancement

#132 Issue#130 find meeting data from token
  src/backend/lib/meeting/findMeetingData.js
  src/backend/router/v2/meeting.js
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
Labels: P0, enhancement

#135 Issue#134 Crawler Minor Refactoring
  src/backend/database/place_crawler.py
Labels: P1, refactoring

#136 Issue#133 Create a Share To Kakao Talk function
  src/frontend/public/index.html
  src/frontend/src/v2/App.js
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
Labels: enhancement

#141 Issue#138-Add selecting transportation And fix some pixels And change font.
  src/frontend/package-lock.json
  src/frontend/public/index.html
  src/frontend/src/images/car.png
  src/frontend/src/images/metro.png
  src/frontend/src/index.css
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
Labels: enhancement

#144 Issue#137 Sort candidate place result
  src/backend/config/API_KEY_template.json
  src/backend/database/place_sorter.py
Labels: P1, enhancement

#142 Issue#139-Add result box.
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
Labels: enhancement

#145 Issue#143 UI alignment and change submit list and add checkbox
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/rwd.css
Labels: enhancement

#146 Issue128-find-result-from-meeting-user-db
  src/backend/db.js
  src/backend/lib/findRoute/candidatesWithUserData.js
  src/backend/lib/meeting/findMeetingData.js
  src/backend/lib/meeting/makeMeetingUser.js
  src/backend/models/CandidateLocs.js
  src/backend/models/MeetingUser.js
  src/backend/router/v2/findRoute.js
  src/backend/router/v2/meeting.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.js
Labels: P0, enhancement

#147 voting function using token
  src/backend/router/v2/voting.js
Labels: P1, enhancement

#153 Issue#152-Change Background. And add three marker image
  src/frontend/src/images/init_back.png
  src/frontend/src/images/marker_blue.png
  src/frontend/src/images/marker_orange.png
  src/frontend/src/images/marker_red.png
  src/frontend/src/v2/MakeRoom.css
Labels: enhancement

#154 Issue#150 name input error
  src/frontend/src/v2/Meeting.js
Labels: bug

#155 Issue#151 show markers
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
Labels: P1, enhancement

#158 Issue#157-Make-submit-status-and-checkbox
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
Labels: enhancement

#160 Issue#159-Change design of Selecting transportation
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
Labels: enhancement

#162 Issue#161-Fix the mobile ui and scroll bar
  src/frontend/src/v2/MakeRoom.js
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.js
  src/frontend/src/v2/rwd.css
Labels: enhancement

#164 Issue#163-Limits input to positive integer And Add and Change scrollb…
  src/frontend/src/v2/MakeRoom.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
Labels: bug, enhancement

#166 sending result including 'vote' value
  src/backend/lib/meeting/findMeetingData.js
Labels: P1, enhancement

#167 Issue#148-request-location-name-by-coordinates
  src/backend/lib/meeting/makeMeetingUser.js
  src/backend/models/MeetingUser.js
  src/backend/router/v2/meeting.js
  src/frontend/src/v2/MakeRoom.js
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
Labels: enhancement

#169 Issue#168-Limit-MakeRoom-input-number-and-PrivateRoom-user-number
  src/frontend/src/v2/MakeRoom.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.css
Labels: bug

#171 Issue#170-Restyle path result.
  src/frontend/src/images/car.png
  src/frontend/src/images/metro.png
  src/frontend/src/images/subway.png
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
Labels: bug, enhancement

#172 transportation change
  src/backend/lib/meeting/makeMeetingUser.js
  src/backend/router/v2/meeting.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
Labels: P1, enhancement

#174 cant use result button when majority dont submit starting point
  src/frontend/src/v2/PrivateRoom.js
Labels: P1, enhancement

#175 make config file
  src/frontend/.gitignore
  src/frontend/src/config/API_KEY_template.json
  src/frontend/src/v2/Meeting.js
Labels: P1, enhancement

#176 go to first page
  src/frontend/src/config/API_KEY_template.json
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
Labels: P2, enhancement

#177 click marker and show result
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/ResultRoom.js
Labels: enhancement

#179 Issue#178 restyle across the board
  src/frontend/src/v2/App.js
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.css
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
Labels: bug, enhancement

#181 vote
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/ResultRoom.js
Labels: P0, enhancement

#182 set search point
  src/backend/lib/findRoute/candidatesWithUserData.js
  src/backend/router/v2/findRoute.js
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
Labels: P1, enhancement

#183 Kakao link
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.js
Labels: P1, enhancement

#185 Issue#184 Extension the scroll range
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
  src/frontend/src/v2/rwd.css
Labels: bug

#186 delete enrolled user
  src/backend/lib/meeting/deleteUser.js
  src/backend/router/v2/meeting.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.js
Labels: P1, enhancement

#187 change meeting user num
  src/backend/lib/meeting/changeMeetingUserNum.js
  src/backend/router/v2/meeting.js
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
Labels: enhancement

#188 change button
  src/frontend/src/v2/Map.js
Labels: enhancement

#190 Issue#189-Redesign resultroom
  src/frontend/package.json
  src/frontend/src/v2/Meeting.css
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
Labels: bug, enhancement

#192 Issue#191 create rating value
  src/backend/database/rate_candidate.py
Labels: P1, enhancement

#193 vote rating
  src/backend/db_rating_update.js
  src/backend/db_with_rating.js
  src/backend/lib/findRoute/candidatesWithUserData.js
  src/backend/models/CandidateLocs.js
  src/backend/router/v2/voting.js
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/v1/PrivateRoom.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
Labels: enhancement

#194 show star
  src/frontend/src/v2/ResultRoom.js
Labels: enhancement

#196 Issue#195-Rearrange and restyle
  src/frontend/package-lock.json
  src/frontend/src/images/marker_green.png
  src/frontend/src/rwd.css
  src/frontend/src/v2/Map.css
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.css
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
  src/frontend/src/v2/rwd.css
Labels: enhancement

#198 Issue#197 bugfix in both pc and mobile version
  src/frontend/src/images/star.svg
  src/frontend/src/rwd.css
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
  src/frontend/src/v2/rwd.css
Labels: bug, enhancement

#203 Bugfix in mobile
  src/frontend/src/index.js
  src/frontend/src/v2/App.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/rwd.css
Labels: bug, enhancement

#204 rating by voted data
  src/backend/db_dummy_rating.js
  src/backend/db_rating_update.js
  src/backend/db_with_rating.js
  src/backend/models/CandidateLocs.js
Labels: enhancement

#205 rating
  src/backend/db_dummy_rating.js
  src/backend/db_rating_update.js
  src/backend/lib/findRoute/candidatesWithUserData.js
  src/backend/models/CandidateLocs.js
Labels: enhancement

#206 Issue#202-create-sort-function-by-rating
  src/backend/db_dummy_rating.js
  src/backend/db_rating_update.js
  src/backend/lib/findRoute/candidatesWithUserData.js
  src/frontend/src/v2/Meeting.js
Labels: P0, enhancement

#208 Issue#207-Restyle
  src/frontend/src/v2/Meeting.css
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
Labels: enhancement

#209 hide information box
  src/frontend/src/v2/Map.js
Labels: enhancement

#210 info window
  src/frontend/src/v2/Map.js
Labels: bug

#212 Issue#211 Fix the scrollHeight and move the votebox
  src/frontend/src/v2/ResultRoom.css
  src/frontend/src/v2/ResultRoom.js
Labels: bug

#214 Bug fix
  src/frontend/src/v2/ResultRoom.js
Labels: bug

#217 revise icon and title
  src/backend/package-lock.json
  src/frontend/package-lock.json
  src/frontend/public/favicon.ico
  src/frontend/public/index.html
  src/frontend/public/manifest.json
  src/frontend/src/v2/MakeRoom.js
Labels: P2

#218 Issue#215-Fix-the-footer-menu-button
  src/frontend/src/rwd.css
  src/frontend/src/v2/rwd.css
Labels: bug

#220 Issue#219-Modify-API-URL
  src/frontend/src/v2/MakeRoom.js
Labels: bug

#221 delete marker click event
  src/frontend/src/v2/Map.js
Labels: enhancement

#223 search point location
  src/frontend/src/v2/Map.css
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/PrivateRoom.css
Labels: enhancement

#225 Issue#224 fix button position
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/rwd.css
Labels: enhancement

#227 Issue#226-Home button in mobile And font
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/PrivateRoom.css
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/rwd.css
Labels: enhancement

#228 Issue#222-Move the mobile share button and change the sentence
  src/frontend/src/v2/MakeRoom.js
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/rwd.css
Labels: P0

#230 Issue#229-Map bug fix
  src/frontend/src/v2/Map.js
Labels: bug

#232 Issue#231-Bugfix and rearrange share button
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/Meeting.css
  src/frontend/src/v2/Meeting.js
  src/frontend/src/v2/rwd.css
Labels: enhancement

#234 Issue#233 maybe last bugfix
  src/frontend/src/v2/Map.js
  src/frontend/src/v2/PrivateRoom.js
  src/frontend/src/v2/rwd.css
Labels: enhancement

#236 Issue#235-Fix room name space
  src/frontend/src/v2/Meeting.css
  src/frontend/src/v2/Meeting.js
Labels: enhancement

#238 Issue#237-Change mobile initial display
  src/frontend/src/v2/rwd.css
Labels: enhancement

#239 hurry up!
  src/frontend/src/v2/Map.js
Labels: enhancement

#241 Issue#240-Bugfix info window
  src/frontend/src/v2/Map.css
Labels: enhancement
